// Bindings not present in wrangler.jsonc (secrets, optional vars) merged into
// the Env interface generated by `wrangler types`.
interface Env {
  /**
   * Optional fallback TripIt OAuth credentials for private single-user
   * deployments (`wrangler secret put TRIPIT_...`, all four required).
   * Normally callers supply their own credentials per-request via the
   * X-TripIt-* headers.
   */
  TRIPIT_CONSUMER_KEY?: string;
  TRIPIT_CONSUMER_SECRET?: string;
  TRIPIT_ACCESS_TOKEN?: string;
  TRIPIT_ACCESS_TOKEN_SECRET?: string;
  /** Zero Trust team domain (e.g. "myteam"). Set with ACCESS_APP_AUD to enforce Access JWT validation. */
  ACCESS_TEAM_DOMAIN?: string;
  /** Audience (AUD) tag of the Cloudflare Access application protecting this Worker. */
  ACCESS_APP_AUD?: string;
}
