// Bindings not present in wrangler.jsonc (secrets, optional vars) merged into
// the Env interface generated by `wrangler types`.
interface Env {
  /**
   * This deployment's registered TripIt API application
   * (`wrangler secret put TRIPIT_CONSUMER_KEY` / `TRIPIT_CONSUMER_SECRET`;
   * register at https://www.tripit.com/developer). When set they enable the
   * hosted /connect browser flow and let callers authenticate with just an
   * access-token pair. Callers with their own TripIt app can always send all
   * four X-TripIt-* headers instead.
   */
  TRIPIT_CONSUMER_KEY?: string;
  TRIPIT_CONSUMER_SECRET?: string;
  /**
   * Optional fallback access-token pair for private single-user deployments
   * (requires the consumer secrets above too): keyless requests then act on
   * this TripIt account. Leave unset on a shared/public server.
   */
  TRIPIT_ACCESS_TOKEN?: string;
  TRIPIT_ACCESS_TOKEN_SECRET?: string;
  /** Zero Trust team domain (e.g. "myteam"). Set with ACCESS_APP_AUD to enforce Access JWT validation. */
  ACCESS_TEAM_DOMAIN?: string;
  /** Audience (AUD) tag of the Cloudflare Access application protecting this Worker. */
  ACCESS_APP_AUD?: string;
}
